// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwZlyMf3qKTFgerVuG85Xv5_24ApK8ejw',
    appId: '1:856040070365:web:5bfae8f947d90853accf34',
    messagingSenderId: '856040070365',
    projectId: 'fluttercrud-43500',
    authDomain: 'fluttercrud-43500.firebaseapp.com',
    storageBucket: 'fluttercrud-43500.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKEIE9oVXoSgo2jLlXEMoczhw2MOyIveY',
    appId: '1:856040070365:android:98563972f7532aa9accf34',
    messagingSenderId: '856040070365',
    projectId: 'fluttercrud-43500',
    storageBucket: 'fluttercrud-43500.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCarXZFaTftUl9UawEsa_rmyKMtmoanfZE',
    appId: '1:856040070365:ios:eb52af204ff14afdaccf34',
    messagingSenderId: '856040070365',
    projectId: 'fluttercrud-43500',
    storageBucket: 'fluttercrud-43500.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCarXZFaTftUl9UawEsa_rmyKMtmoanfZE',
    appId: '1:856040070365:ios:eb52af204ff14afdaccf34',
    messagingSenderId: '856040070365',
    projectId: 'fluttercrud-43500',
    storageBucket: 'fluttercrud-43500.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationFirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwZlyMf3qKTFgerVuG85Xv5_24ApK8ejw',
    appId: '1:856040070365:web:00d9a6a5de8e3074accf34',
    messagingSenderId: '856040070365',
    projectId: 'fluttercrud-43500',
    authDomain: 'fluttercrud-43500.firebaseapp.com',
    storageBucket: 'fluttercrud-43500.firebasestorage.app',
  );

}